# ABI contract interaction — function signature parsing, calldata encoding/decoding, read/write calls
# sig format includes return type, e.g. "balanceOf(address)->(uint256)", generated by list_functions
# Arguments are auto-converted based on signature types: address→checksum, uint→int, bool→true/false, bytes→hex, tuple/array→JSON

import json
from pathlib import Path
from typing import Any
from web3 import Web3
from eth_abi import encode, decode

_SCRIPT_DIR = Path(__file__).resolve().parent
_SKILL_DIR = _SCRIPT_DIR.parent

try:
    from .chains import get_w3
    from .wallet import _send_tx
    from .fetch_abi import fetch_abi
except ImportError:
    from chains import get_w3
    from wallet import _send_tx
    from fetch_abi import fetch_abi

# (path_or_address) -> list[dict]  Load ABI JSON; bare filenames resolved relative to scripts/ then abis/; contract addresses auto-fetched
def _load(path: str) -> list[dict]:
    p = Path(path)
    if not p.is_absolute() and not p.exists():
        p = _SCRIPT_DIR / path
    if not p.exists():
        p = _SKILL_DIR / "abis" / Path(path).name
    if not p.exists():
        # Treat as contract address, fetch ABI
        p = Path(fetch_abi(path))
    with open(p) as f:
        return json.load(f)

# (sig) -> (canonical_sig, input_types, output_types)  Parse function signature
def _parse_sig(sig: str) -> tuple[str, list[str], list[str]]:
    left, rest = sig.split("(", 1)
    if ")->(" in rest:
        in_str, out_str = rest.split(")->(", 1)
        out_str = out_str.rstrip(")")
    else:
        in_str = rest.rstrip(")")
        out_str = ""
    in_types = [t.strip() for t in in_str.split(",")] if in_str else []
    out_types = [t.strip() for t in out_str.split(",")] if out_str else []
    canon = f"{left}({','.join(in_types)})"
    return canon, in_types, out_types

# (value, abi_type) -> Any  Auto-convert argument value based on ABI type
def _convert_arg(value: Any, abi_type: str) -> Any:
    if abi_type == "address":
        return Web3.to_checksum_address(value)
    if abi_type.startswith("uint") or abi_type.startswith("int"):
        return int(value)
    if abi_type == "bool":
        return value.lower() in ("true", "1", "yes") if isinstance(value, str) else bool(value)
    if abi_type == "string":
        return value
    if abi_type.startswith("bytes"):
        return bytes.fromhex(value.removeprefix("0x")) if isinstance(value, str) else value
    if abi_type.endswith("[]") or abi_type.startswith("tuple"):
        return json.loads(value) if isinstance(value, str) else value
    return value

# (value) -> Any  Serialize on-chain return values to JSON-safe types (bytes→hex, large integers→str)
def _serialize(value: Any) -> Any:
    if isinstance(value, bytes):
        return "0x" + value.hex()
    if isinstance(value, int):
        return value if abs(value) < 2**53 else str(value)
    if isinstance(value, (list, tuple)):
        return [_serialize(v) for v in value]
    return value

# (abi_json) -> {read: [sig, ...], write: [sig, ...]}  Parse ABI JSON file; sigs can be passed directly to call/invoke
def list_functions(abi_json: str) -> dict[str, list[str]]:
    read_fns, write_fns = [], []
    for item in _load(abi_json):
        if item.get("type") != "function":
            continue
        ins = ",".join(i["type"] for i in item.get("inputs", []))
        outs = ",".join(o["type"] for o in item.get("outputs", []))
        sig = f"{item['name']}({ins})"
        if outs:
            sig += f"->({outs})"
        (read_fns if item.get("stateMutability") in ("view", "pure") else write_fns).append(sig)
    return {"read": read_fns, "write": write_fns}

# (address, sig, args, chain_id) -> Any  Call a read-only contract function (view/pure), no private key needed, return value auto-serialized
def call(address: str, sig: str, args: list[str] | None = None, *, chain_id: int = 10, from_address: str | None = None) -> Any:
    canon, in_types, out_types = _parse_sig(sig)
    selector = Web3.keccak(text=canon)[:4]
    converted = [_convert_arg(a, t) for a, t in zip(args or [], in_types)]
    data = selector + encode(in_types, converted) if converted else selector
    tx = {"to": Web3.to_checksum_address(address), "data": data}
    if from_address is not None:
        tx["from"] = Web3.to_checksum_address(from_address)
    raw = get_w3(chain_id).eth.call(tx)
    if not out_types:
        return "0x" + raw.hex() if raw else None
    result = decode(out_types, raw)
    return _serialize(result[0]) if len(result) == 1 else _serialize(list(result))

# (sig, args) -> bytes  Encode function call as calldata (selector + encoded args)
def _invoke(sig: str, args: list[str] | None = None) -> bytes:
    canon, in_types, _ = _parse_sig(sig)
    selector = Web3.keccak(text=canon)[:4]
    converted = [_convert_arg(a, t) for a, t in zip(args or [], in_types)]
    return selector + encode(in_types, converted) if converted else selector

# (address, sig, args, chain_id, value) -> receipt  Call a write function and send the transaction, returns standard EVM transaction receipt
def invoke(address: str, sig: str, args: list[str] | None = None, *, chain_id: int = 10, value: int = 0) -> dict:
    data = _invoke(sig, args)
    return _send_tx(address, chain_id=chain_id, value=value, data=data)
